/** Textos em português para a animação do journey (homepage). */
import type { JourneyEvent, Lane, Phase } from '@/lib/journey-data';

export const PHASES_PT: Phase[] = [
  { id: 'before', label: 'Antes da chegada', range: 'D-7 → D-1', from: 0.0, to: 0.22 },
  { id: 'arrival', label: 'Chegada', range: 'Check-in', from: 0.22, to: 0.36 },
  { id: 'stay', label: 'Durante a estadia', range: 'D+1 → D+n', from: 0.36, to: 0.66 },
  { id: 'departure', label: 'Partida', range: 'D+n', from: 0.66, to: 0.86 },
  { id: 'after', label: 'Após a estadia', range: 'D+1 → D+2', from: 0.86, to: 1.0 },
];

export const LANES_PT: Lane[] = [
  { id: 0, label: 'GUEST', sublabel: 'Hóspede', color: '#06b6d4' },
  { id: 1, label: 'SOJORI', sublabel: 'Orquestrador', color: '#e6b022' },
  { id: 2, label: 'STAFF', sublabel: 'Equipa no local', color: '#8b5cf6' },
  { id: 3, label: 'ADMIN', sublabel: 'Supervisor', color: '#ef4444' },
];

export const EVENTS_PT: JourneyEvent[] = [
  {
    id: 'booking',
    t: 0.0,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🏠',
    title: 'Reserva Airbnb',
    sub: 'Sarah J. · 3 noites · 840 €',
    status: 'completed',
    anim: 'confetti',
    tag: 'D-14',
    transitions: [{ at: 0.02, status: 'completed', sub: 'Sincronização automática → calendário · pagamento confirmado', tag: 'Sinc.' }],
  },
  {
    id: 'staff-prep',
    t: 0.03,
    lane: 2,
    phase: 'before',
    type: 'staff',
    icon: '👨‍🔧',
    title: 'Preparação do alojamento',
    sub: 'Lucas · controlo de qualidade',
    status: 'active',
    anim: 'slide-right',
    tag: 'D-1',
    avatar: 'L',
    transitions: [{ at: 0.06, status: 'completed', sub: 'Qualidade ✓ · stock ✓ · chaves ✓', tag: 'Pronto' }],
  },
  {
    id: 'welcome',
    t: 0.05,
    lane: 0,
    phase: 'before',
    type: 'message',
    icon: '📨',
    title: 'Mensagem de boas-vindas',
    sub: '« Bem-vindo a Paris! A sua estadia começa em breve »',
    status: 'completed',
    anim: 'fade',
    tag: 'D-7',
  },
  {
    id: 'register',
    t: 0.08,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🔐',
    title: 'Registo',
    sub: 'KYC em curso…',
    status: 'pending',
    anim: 'pop',
    tag: 'Em curso',
    transitions: [{ at: 0.14, status: 'completed', sub: 'Identidade verificada em 30 segundos', tag: 'Verificado' }],
  },
  {
    id: 'arrival-slot',
    t: 0.12,
    lane: 0,
    phase: 'before',
    type: 'timeslot',
    icon: '🎫',
    title: 'Janela de chegada',
    sub: '16:00 — 17:00',
    status: 'info',
    anim: 'pop',
    tag: 'Horário',
    transitions: [{ at: 0.2, status: 'completed', tag: 'Confirmado' }],
  },
  {
    id: 'kids-club',
    t: 0.16,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '👶',
    title: 'Kids club pedido',
    sub: 'Serviço de babysitting',
    status: 'pending',
    anim: 'pop',
    tag: 'Opcional',
    transitions: [{ at: 0.21, status: 'completed', sub: 'Kids club reservado · 2 crianças', tag: 'Confirmado' }],
  },
  {
    id: 'airport-shuttle',
    t: 0.18,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '✈️',
    title: 'Shuttle aeroporto',
    sub: 'Transfer à chegada',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Transporte',
    transitions: [{ at: 0.22, status: 'completed', sub: 'Motorista confirmado · voo AA123', tag: 'Planificado' }],
  },
  {
    id: 'arrived',
    t: 0.24,
    lane: 0,
    phase: 'arrival',
    type: 'declaration',
    icon: '🏨',
    title: 'Hóspede chegou',
    sub: 'GPS + QR · autodeclarado',
    status: 'completed',
    anim: 'pop',
    tag: 'Dia J',
  },
  {
    id: 'admin-conflict',
    t: 0.27,
    lane: 3,
    phase: 'arrival',
    type: 'admin',
    icon: '⚠️',
    title: 'Conflito de agenda',
    sub: 'O hóspede anterior não declarou a partida',
    status: 'late',
    anim: 'shake',
    tag: 'Bloqueado',
    transitions: [
      { at: 0.29, status: 'active', sub: 'Admin contacta hóspede de saída · hora de partida?', tag: 'Em curso', icon: '📞' },
      { at: 0.32, status: 'completed', sub: 'Saída 14h confirmada · nova chegada 16h OK', tag: 'Resolvido', icon: '✓' },
    ],
  },
  {
    id: 'feedback',
    t: 0.38,
    lane: 0,
    phase: 'stay',
    type: 'message',
    icon: '💬',
    title: 'Mensagem de feedback',
    sub: '« Como está a sua estadia? »',
    status: 'info',
    anim: 'bubble',
    tag: 'D+1',
  },
  {
    id: 'clean-mid',
    t: 0.42,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧹',
    title: 'Limpeza incluída — dia 3',
    sub: 'Agendada · lembrete D-2',
    status: 'soon',
    anim: 'cascade',
    tag: 'Agendada',
    transitions: [
      { at: 0.46, status: 'pending', sub: 'Em breve · equipa notificada', tag: 'Em breve' },
      { at: 0.5, status: 'active', sub: 'Sophie a caminho', tag: 'Atribuída', avatar: 'S' },
      { at: 0.55, status: 'completed', sub: 'Limpeza feita · impecável', tag: 'OK', icon: '✅' },
    ],
  },
  {
    id: 'transport',
    t: 0.46,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🚗',
    title: 'Transfer aeroporto',
    sub: 'Pedido do hóspede',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Opcional',
    transitions: [{ at: 0.52, status: 'completed', sub: 'Motorista atribuído · ETA 16:23', tag: 'Confirmado' }],
  },
  {
    id: 'groceries',
    t: 0.5,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🛍️',
    title: 'Compras',
    sub: 'Pedido do hóspede',
    status: 'pending',
    anim: 'pop',
    tag: 'Opcional',
    transitions: [{ at: 0.56, status: 'completed', sub: 'Frigorífico cheio antes da chegada', tag: 'Entregue' }],
  },
  {
    id: 'wifi-issue',
    t: 0.52,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '📶',
    title: 'Ticket Wi-Fi',
    sub: 'Problema de ligação reportado',
    status: 'late',
    anim: 'shake',
    tag: 'Urgente',
    transitions: [
      { at: 0.52, status: 'active', sub: 'Equipa atribuída já · Marc a caminho', tag: 'Atribuído', avatar: 'M' },
      { at: 0.54, status: 'active', sub: 'Técnico no local · diagnóstico', tag: 'Em curso' },
      { at: 0.56, status: 'completed', sub: 'Wi-Fi restabelecido · teste de velocidade OK', tag: 'Resolvido' },
    ],
  },
  {
    id: 'support',
    t: 0.54,
    lane: 1,
    phase: 'stay',
    type: 'request',
    icon: '✨',
    title: 'Suporte dedicado',
    sub: 'Concierge privado',
    status: 'active',
    anim: 'pop',
    tag: 'Premium',
  },
  {
    id: 'extra-clean',
    t: 0.58,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧼',
    title: 'Limpeza extra',
    sub: 'Serviço sob demanda',
    status: 'pending',
    anim: 'cascade',
    tag: 'EXTRA · 25 €',
    transitions: [{ at: 0.63, status: 'completed', sub: 'Limpeza feita · 28 min', tag: 'Feito' }],
  },
  {
    id: 'depart-instr',
    t: 0.68,
    lane: 0,
    phase: 'departure',
    type: 'message',
    icon: '📋',
    title: 'Instruções de partida',
    sub: '« Tudo o que precisa de saber »',
    status: 'info',
    anim: 'fade',
    tag: 'D-1',
  },
  {
    id: 'depart-slot',
    t: 0.71,
    lane: 0,
    phase: 'departure',
    type: 'timeslot',
    icon: '🎫',
    title: 'Janela de partida',
    sub: '11:00',
    status: 'info',
    anim: 'pop',
    tag: 'Horário',
    transitions: [{ at: 0.76, status: 'completed', tag: 'Confirmado' }],
  },
  {
    id: 'staff-late',
    t: 0.73,
    lane: 3,
    phase: 'departure',
    type: 'admin',
    icon: '🚨',
    title: 'Staff em falta',
    sub: 'Reatribuição necessária',
    status: 'late',
    anim: 'shake',
    tag: 'Urgente',
    transitions: [{ at: 0.78, status: 'completed', sub: 'Reatribuído a Marc · 2 min', tag: 'Resolvido', icon: '👨‍💼' }],
  },
  {
    id: 'departed',
    t: 0.79,
    lane: 0,
    phase: 'departure',
    type: 'declaration',
    icon: '✅',
    title: 'Hóspede saiu',
    sub: 'Check-out declarado',
    status: 'completed',
    anim: 'confetti',
    tag: 'Feito',
  },
  {
    id: 'final-clean',
    t: 0.81,
    lane: 2,
    phase: 'departure',
    type: 'cleaning',
    icon: '🧹',
    title: 'Limpeza final Sojori',
    sub: '2h antes da próxima reserva',
    status: 'late',
    anim: 'priority',
    tag: 'PRIORIDADE',
    priority: true,
    transitions: [
      { at: 0.84, status: 'pending', sub: '1h30 · Marc no local', tag: 'Em curso', avatar: 'M' },
      {
        at: 0.86,
        status: 'completed',
        sub: 'Pronto para a próxima reserva · alojamento pronto',
        tag: '✓ Pronto',
        icon: '✅',
        priority: false,
      },
    ],
  },
  {
    id: 'thanks',
    t: 0.88,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '🙏',
    title: 'Mensagem de agradecimento',
    sub: '« Até breve com Sojori »',
    status: 'info',
    anim: 'fade',
    tag: 'D+1',
  },
  {
    id: 'review',
    t: 0.93,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '⭐',
    title: 'Pedido de avaliação',
    sub: 'Avaliação 5 estrelas recebida',
    status: 'completed',
    anim: 'stars',
    tag: 'D+2',
  },
];
