/** نصوص العربية لرسوم الجولي (الصفحة الرئيسية). */
import type { JourneyEvent, Lane, Phase } from '@/lib/journey-data';

export const PHASES_AR: Phase[] = [
  { id: 'before', label: 'قبل الوصول', range: 'D-7 → D-1', from: 0.0, to: 0.22 },
  { id: 'arrival', label: 'الوصول', range: 'يوم الوصول', from: 0.22, to: 0.36 },
  { id: 'stay', label: 'أثناء الإقامة', range: 'D+1 → D+n', from: 0.36, to: 0.66 },
  { id: 'departure', label: 'المغادرة', range: 'D+n', from: 0.66, to: 0.86 },
  { id: 'after', label: 'بعد الإقامة', range: 'D+1 → D+2', from: 0.86, to: 1.0 },
];

export const LANES_AR: Lane[] = [
  { id: 0, label: 'GUEST', sublabel: 'الضيف', color: '#06b6d4' },
  { id: 1, label: 'SOJORI', sublabel: 'المُنسِق', color: '#e6b022' },
  { id: 2, label: 'STAFF', sublabel: 'الفريق الميداني', color: '#8b5cf6' },
  { id: 3, label: 'ADMIN', sublabel: 'المشرف', color: '#ef4444' },
];

export const EVENTS_AR: JourneyEvent[] = [
  {
    id: 'booking',
    t: 0.0,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🏠',
    title: 'حجز Airbnb',
    sub: 'Sarah J. · 3 ليالٍ · 840 €',
    status: 'completed',
    anim: 'confetti',
    tag: 'D-14',
    transitions: [{ at: 0.02, status: 'completed', sub: 'مزامنة تلقائية ← التقويم · الدفع مؤكد', tag: 'متزامن' }],
  },
  {
    id: 'staff-prep',
    t: 0.03,
    lane: 2,
    phase: 'before',
    type: 'staff',
    icon: '👨‍🔧',
    title: 'تجهيز العقار',
    sub: 'Lucas · فحص الجودة',
    status: 'active',
    anim: 'slide-right',
    tag: 'D-1',
    avatar: 'L',
    transitions: [{ at: 0.06, status: 'completed', sub: 'جودة ✓ · مخزون ✓ · مفاتيح ✓', tag: 'جاهز' }],
  },
  {
    id: 'welcome',
    t: 0.05,
    lane: 0,
    phase: 'before',
    type: 'message',
    icon: '📨',
    title: 'رسالة ترحيب',
    sub: '« مرحباً بك في باريس! إقامتك تبدأ قريباً »',
    status: 'completed',
    anim: 'fade',
    tag: 'D-7',
  },
  {
    id: 'register',
    t: 0.08,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🔐',
    title: 'التسجيل',
    sub: 'التحقق من الهوية جارٍ…',
    status: 'pending',
    anim: 'pop',
    tag: 'قيد التنفيذ',
    transitions: [{ at: 0.14, status: 'completed', sub: 'تم التحقق من الهوية في 30 ثانية', tag: 'مُوثّق' }],
  },
  {
    id: 'arrival-slot',
    t: 0.12,
    lane: 0,
    phase: 'before',
    type: 'timeslot',
    icon: '🎫',
    title: 'نافذة الوصول',
    sub: '16:00 — 17:00',
    status: 'info',
    anim: 'pop',
    tag: 'موعد',
    transitions: [{ at: 0.2, status: 'completed', tag: 'مؤكد' }],
  },
  {
    id: 'kids-club',
    t: 0.16,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '👶',
    title: 'طلب نادي الأطفال',
    sub: 'خدمة رعاية الأطفال',
    status: 'pending',
    anim: 'pop',
    tag: 'اختياري',
    transitions: [{ at: 0.21, status: 'completed', sub: 'تم حجز نادي الأطفال · طفلان', tag: 'مؤكد' }],
  },
  {
    id: 'airport-shuttle',
    t: 0.18,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '✈️',
    title: 'نقل المطار',
    sub: 'طلب انتقال عند الوصول',
    status: 'pending',
    anim: 'slide-right',
    tag: 'نقل',
    transitions: [{ at: 0.22, status: 'completed', sub: 'سائق مؤكد · رحلة AA123', tag: 'مجدول' }],
  },
  {
    id: 'arrived',
    t: 0.24,
    lane: 0,
    phase: 'arrival',
    type: 'declaration',
    icon: '🏨',
    title: 'وصول الضيف',
    sub: 'GPS + QR · إقرار ذاتي',
    status: 'completed',
    anim: 'pop',
    tag: 'يوم الوصول',
  },
  {
    id: 'admin-conflict',
    t: 0.27,
    lane: 3,
    phase: 'arrival',
    type: 'admin',
    icon: '⚠️',
    title: 'تعارض في الجدول',
    sub: 'الضيف السابق لم يصرّح بالمغادرة',
    status: 'late',
    anim: 'shake',
    tag: 'محظور',
    transitions: [
      { at: 0.29, status: 'active', sub: 'المشرف يتصل بالضيف المغادر · ما وقت المغادرة؟', tag: 'قيد التنفيذ', icon: '📞' },
      { at: 0.32, status: 'completed', sub: 'مغادرة 14:00 مؤكدة · وصول جديد 16:00 موافق', tag: 'تم الحل', icon: '✓' },
    ],
  },
  {
    id: 'feedback',
    t: 0.38,
    lane: 0,
    phase: 'stay',
    type: 'message',
    icon: '💬',
    title: 'رسالة تقييم',
    sub: '« كيف تسير إقامتك؟ »',
    status: 'info',
    anim: 'bubble',
    tag: 'D+1',
  },
  {
    id: 'clean-mid',
    t: 0.42,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧹',
    title: 'تنظيف مشمول — اليوم 3',
    sub: 'مجدول · تذكير D-2',
    status: 'soon',
    anim: 'cascade',
    tag: 'مجدول',
    transitions: [
      { at: 0.46, status: 'pending', sub: 'قريباً · تم إخطار الفريق', tag: 'قريباً' },
      { at: 0.5, status: 'active', sub: 'Sophie في الطريق', tag: 'مُعيّن', avatar: 'S' },
      { at: 0.55, status: 'completed', sub: 'تم التنظيف · لامع', tag: 'تمام', icon: '✅' },
    ],
  },
  {
    id: 'transport',
    t: 0.46,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🚗',
    title: 'نقل المطار',
    sub: 'طلب الضيف',
    status: 'pending',
    anim: 'slide-right',
    tag: 'اختياري',
    transitions: [{ at: 0.52, status: 'completed', sub: 'سائق مُعيّن · الوصول المتوقع 16:23', tag: 'مؤكد' }],
  },
  {
    id: 'groceries',
    t: 0.5,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🛍️',
    title: 'التسوق',
    sub: 'طلب الضيف',
    status: 'pending',
    anim: 'pop',
    tag: 'اختياري',
    transitions: [{ at: 0.56, status: 'completed', sub: 'الثلاجة ممتلئة قبل الوصول', tag: 'تم التسليم' }],
  },
  {
    id: 'wifi-issue',
    t: 0.52,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '📶',
    title: 'تذكرة دعم الواي فاي',
    sub: 'تم الإبلاغ عن مشكلة اتصال',
    status: 'late',
    anim: 'shake',
    tag: 'عاجل',
    transitions: [
      { at: 0.52, status: 'active', sub: 'تعيين فوري للفريق · Marc في الطريق', tag: 'مُعيّن', avatar: 'M' },
      { at: 0.54, status: 'active', sub: 'فني في الموقع · تشخيص', tag: 'قيد التنفيذ' },
      { at: 0.56, status: 'completed', sub: 'تم استعادة الواي فاي · السرعة ضمن المعدل الطبيعي', tag: 'تم الحل' },
    ],
  },
  {
    id: 'support',
    t: 0.54,
    lane: 1,
    phase: 'stay',
    type: 'request',
    icon: '✨',
    title: 'دعم مخصص',
    sub: 'كونسييرج خاص',
    status: 'active',
    anim: 'pop',
    tag: 'مميز',
  },
  {
    id: 'extra-clean',
    t: 0.58,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧼',
    title: 'تنظيف إضافي',
    sub: 'خدمة عند الطلب',
    status: 'pending',
    anim: 'cascade',
    tag: 'EXTRA · 25 €',
    transitions: [{ at: 0.63, status: 'completed', sub: 'تم التنظيف · 28 دقيقة', tag: 'تم' }],
  },
  {
    id: 'depart-instr',
    t: 0.68,
    lane: 0,
    phase: 'departure',
    type: 'message',
    icon: '📋',
    title: 'تعليمات المغادرة',
    sub: '« كل ما تحتاج معرفته »',
    status: 'info',
    anim: 'fade',
    tag: 'D-1',
  },
  {
    id: 'depart-slot',
    t: 0.71,
    lane: 0,
    phase: 'departure',
    type: 'timeslot',
    icon: '🎫',
    title: 'نافذة المغادرة',
    sub: '11:00',
    status: 'info',
    anim: 'pop',
    tag: 'موعد',
    transitions: [{ at: 0.76, status: 'completed', tag: 'مؤكد' }],
  },
  {
    id: 'staff-late',
    t: 0.73,
    lane: 3,
    phase: 'departure',
    type: 'admin',
    icon: '🚨',
    title: 'غياب الطاقم',
    sub: 'يلزم إعادة تعيين',
    status: 'late',
    anim: 'shake',
    tag: 'عاجل',
    transitions: [{ at: 0.78, status: 'completed', sub: 'إعادة تعيين إلى Marc · دقيقتان', tag: 'تم الحل', icon: '👨‍💼' }],
  },
  {
    id: 'departed',
    t: 0.79,
    lane: 0,
    phase: 'departure',
    type: 'declaration',
    icon: '✅',
    title: 'مغادرة الضيف',
    sub: 'تم الإقرار بتسجيل المغادرة',
    status: 'completed',
    anim: 'confetti',
    tag: 'تم',
  },
  {
    id: 'final-clean',
    t: 0.81,
    lane: 2,
    phase: 'departure',
    type: 'cleaning',
    icon: '🧹',
    title: 'التنظيف النهائي Sojori',
    sub: 'ساعتان قبل الحجز التالي',
    status: 'late',
    anim: 'priority',
    tag: 'أولوية',
    priority: true,
    transitions: [
      { at: 0.84, status: 'pending', sub: 'Marc في الموقع · متبقي 90 د', tag: 'قيد التنفيذ', avatar: 'M' },
      {
        at: 0.86,
        status: 'completed',
        sub: 'جاهز للحجز التالي · العقار جاهز',
        tag: '✓ جاهز',
        icon: '✅',
        priority: false,
      },
    ],
  },
  {
    id: 'thanks',
    t: 0.88,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '🙏',
    title: 'رسالة شكر',
    sub: '« إلى اللقاء مع Sojori »',
    status: 'info',
    anim: 'fade',
    tag: 'D+1',
  },
  {
    id: 'review',
    t: 0.93,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '⭐',
    title: 'طلب مراجعة',
    sub: 'تم استلام تقييم 5 نجوم',
    status: 'completed',
    anim: 'stars',
    tag: 'D+2',
  },
];
