/** Textos en español para la animación del journey (homepage). */
import type { JourneyEvent, Lane, Phase } from '@/lib/journey-data';

export const PHASES_ES: Phase[] = [
  { id: 'before', label: 'Antes de la llegada', range: 'D-7 → D-1', from: 0.0, to: 0.22 },
  { id: 'arrival', label: 'Llegada', range: 'Check-in', from: 0.22, to: 0.36 },
  { id: 'stay', label: 'Durante la estancia', range: 'D+1 → D+n', from: 0.36, to: 0.66 },
  { id: 'departure', label: 'Salida', range: 'D+n', from: 0.66, to: 0.86 },
  { id: 'after', label: 'Después de la estancia', range: 'D+1 → D+2', from: 0.86, to: 1.0 },
];

export const LANES_ES: Lane[] = [
  { id: 0, label: 'GUEST', sublabel: 'Huésped', color: '#06b6d4' },
  { id: 1, label: 'SOJORI', sublabel: 'Orquestador', color: '#e6b022' },
  { id: 2, label: 'STAFF', sublabel: 'Equipo en destino', color: '#8b5cf6' },
  { id: 3, label: 'ADMIN', sublabel: 'Supervisor', color: '#ef4444' },
];

export const EVENTS_ES: JourneyEvent[] = [
  {
    id: 'booking',
    t: 0.0,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🏠',
    title: 'Reserva Airbnb',
    sub: 'Sarah J. · 3 noches · €840',
    status: 'completed',
    anim: 'confetti',
    tag: 'D-14',
    transitions: [{ at: 0.02, status: 'completed', sub: 'Sync calendario · pago OK', tag: 'Sinc.' }],
  },
  {
    id: 'staff-prep',
    t: 0.03,
    lane: 2,
    phase: 'before',
    type: 'staff',
    icon: '👨‍🔧',
    title: 'Preparación alojamiento',
    sub: 'Lucas · control calidad',
    status: 'active',
    anim: 'slide-right',
    tag: 'D-1',
    avatar: 'L',
    transitions: [{ at: 0.06, status: 'completed', sub: 'Calidad ✓ · Stock ✓ · Llaves ✓', tag: 'Listo' }],
  },
  {
    id: 'welcome',
    t: 0.05,
    lane: 0,
    phase: 'before',
    type: 'message',
    icon: '📨',
    title: 'Mensaje bienvenida',
    sub: '¡Bienvenido a París!',
    status: 'completed',
    anim: 'fade',
    tag: 'D-7',
  },
  {
    id: 'register',
    t: 0.08,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🔐',
    title: 'Registro',
    sub: 'KYC en curso…',
    status: 'pending',
    anim: 'pop',
    tag: 'En curso',
    transitions: [{ at: 0.14, status: 'completed', sub: 'Identidad verificada · 30s', tag: 'Verificado' }],
  },
  {
    id: 'arrival-slot',
    t: 0.12,
    lane: 0,
    phase: 'before',
    type: 'timeslot',
    icon: '🎫',
    title: 'Franja llegada',
    sub: '16:00 — 17:00',
    status: 'info',
    anim: 'pop',
    tag: 'Horario',
    transitions: [{ at: 0.2, status: 'completed', tag: 'Confirmado' }],
  },
  {
    id: 'kids-club',
    t: 0.16,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '👶',
    title: 'Kids Club',
    sub: 'Guardería solicitada',
    status: 'pending',
    anim: 'pop',
    tag: 'Opcional',
    transitions: [{ at: 0.21, status: 'completed', sub: 'Reservado · 2 niños', tag: 'Confirmado' }],
  },
  {
    id: 'airport-shuttle',
    t: 0.18,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '✈️',
    title: 'Shuttle aeropuerto',
    sub: 'Traslado solicitado',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Transporte',
    transitions: [{ at: 0.22, status: 'completed', sub: 'Conductor · Vuelo AA123', tag: 'Planificado' }],
  },
  {
    id: 'arrived',
    t: 0.24,
    lane: 0,
    phase: 'arrival',
    type: 'declaration',
    icon: '🏨',
    title: 'Huésped llegado',
    sub: 'GPS · autodeclarado',
    status: 'completed',
    anim: 'pop',
    tag: 'Día J',
  },
  {
    id: 'admin-conflict',
    t: 0.27,
    lane: 3,
    phase: 'arrival',
    type: 'admin',
    icon: '⚠️',
    title: 'Conflicto agenda',
    sub: 'Salida no declarada',
    status: 'late',
    anim: 'shake',
    tag: 'Bloqueado',
    transitions: [
      { at: 0.29, status: 'active', sub: 'Contacto huésped saliente', tag: 'En curso', icon: '📞' },
      { at: 0.32, status: 'completed', sub: 'Salida 14h · Llegada 16h OK', tag: 'Resuelto', icon: '✓' },
    ],
  },
  {
    id: 'feedback',
    t: 0.38,
    lane: 0,
    phase: 'stay',
    type: 'message',
    icon: '💬',
    title: 'Mensaje feedback',
    sub: 'Satisfacción · D+1',
    status: 'info',
    anim: 'bubble',
    tag: 'D+1',
  },
  {
    id: 'clean-mid',
    t: 0.42,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧹',
    title: 'Limpieza incluida D+3',
    sub: 'Planificada · D+3',
    status: 'soon',
    anim: 'cascade',
    tag: 'Programada',
    transitions: [
      { at: 0.46, status: 'pending', sub: 'Staff notificado', tag: 'Pronto' },
      { at: 0.5, status: 'active', sub: 'Sophie en camino', tag: 'Asignada', avatar: 'S' },
      { at: 0.55, status: 'completed', sub: 'Efectuada · impecable', tag: 'OK', icon: '✅' },
    ],
  },
  {
    id: 'transport',
    t: 0.46,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🚗',
    title: 'Traslado aeropuerto',
    sub: 'Petición huésped',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Opcional',
    transitions: [{ at: 0.52, status: 'completed', sub: 'Conductor · ETA 16:23', tag: 'Confirmado' }],
  },
  {
    id: 'groceries',
    t: 0.5,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🛍️',
    title: 'Compra',
    sub: 'Petición huésped',
    status: 'pending',
    anim: 'pop',
    tag: 'Opcional',
    transitions: [{ at: 0.56, status: 'completed', sub: 'Nevera llena', tag: 'Entregado' }],
  },
  {
    id: 'wifi-issue',
    t: 0.52,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '📶',
    title: 'Ticket Wi-Fi',
    sub: 'Conexión reportada',
    status: 'late',
    anim: 'shake',
    tag: 'Urgente',
    transitions: [
      { at: 0.52, status: 'active', sub: 'Marc en camino', tag: 'Asignado', avatar: 'M' },
      { at: 0.54, status: 'active', sub: 'Diagnóstico en curso', tag: 'En curso' },
      { at: 0.56, status: 'completed', sub: 'WiFi restablecido · OK', tag: 'Resuelto' },
    ],
  },
  {
    id: 'support',
    t: 0.54,
    lane: 1,
    phase: 'stay',
    type: 'request',
    icon: '✨',
    title: 'Soporte dedicado',
    sub: 'Conserje dedicado',
    status: 'active',
    anim: 'pop',
    tag: 'Premium',
  },
  {
    id: 'extra-clean',
    t: 0.58,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧼',
    title: 'Limpieza extra',
    sub: 'Bajo demanda',
    status: 'pending',
    anim: 'cascade',
    tag: 'EXTRA · 25 €',
    transitions: [{ at: 0.63, status: 'completed', sub: 'Efectuada · 28 min', tag: 'Hecho' }],
  },
  {
    id: 'depart-instr',
    t: 0.68,
    lane: 0,
    phase: 'departure',
    type: 'message',
    icon: '📋',
    title: 'Instrucciones salida',
    sub: 'Instrucciones enviadas',
    status: 'info',
    anim: 'fade',
    tag: 'D-1',
  },
  {
    id: 'depart-slot',
    t: 0.71,
    lane: 0,
    phase: 'departure',
    type: 'timeslot',
    icon: '🎫',
    title: 'Franja salida',
    sub: '11:00',
    status: 'info',
    anim: 'pop',
    tag: 'Horario',
    transitions: [{ at: 0.76, status: 'completed', tag: 'Confirmado' }],
  },
  {
    id: 'staff-late',
    t: 0.73,
    lane: 3,
    phase: 'departure',
    type: 'admin',
    icon: '🚨',
    title: 'Staff ausente',
    sub: 'Reasignación necesaria',
    status: 'late',
    anim: 'shake',
    tag: 'Urgente',
    transitions: [{ at: 0.78, status: 'completed', sub: 'Reasignado a Marc · 2 min', tag: 'Resuelto', icon: '👨‍💼' }],
  },
  {
    id: 'departed',
    t: 0.79,
    lane: 0,
    phase: 'departure',
    type: 'declaration',
    icon: '✅',
    title: 'Huésped salido',
    sub: 'Check-out declarado',
    status: 'completed',
    anim: 'confetti',
    tag: 'Hecho',
  },
  {
    id: 'final-clean',
    t: 0.81,
    lane: 2,
    phase: 'departure',
    type: 'cleaning',
    icon: '🧹',
    title: 'Limpieza final',
    sub: 'Próxima reserva en 2h',
    status: 'late',
    anim: 'priority',
    tag: 'PRIORIDAD',
    priority: true,
    transitions: [
      { at: 0.84, status: 'pending', sub: 'Marc en sitio · 1h30', tag: 'En curso', avatar: 'M' },
      {
        at: 0.86,
        status: 'completed',
        sub: 'Alojamiento listo',
        tag: '✓ Listo',
        icon: '✅',
        priority: false,
      },
    ],
  },
  {
    id: 'thanks',
    t: 0.88,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '🙏',
    title: 'Mensaje gracias',
    sub: '¡Hasta pronto!',
    status: 'info',
    anim: 'fade',
    tag: 'D+1',
  },
  {
    id: 'review',
    t: 0.93,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '⭐',
    title: 'Reseña',
    sub: '5 estrellas recibidas',
    status: 'completed',
    anim: 'stars',
    tag: 'D+2',
  },
];
