/**
 * English copy for the homepage journey animation (non-FR locales use this bundle).
 */
import type { JourneyEvent, Lane, Phase } from '@/lib/journey-data';

export const PHASES_EN: Phase[] = [
  { id: 'before', label: 'Before arrival', range: 'D-7 → D-1', from: 0.0, to: 0.22 },
  { id: 'arrival', label: 'Arrival', range: 'Check-in', from: 0.22, to: 0.36 },
  { id: 'stay', label: 'During the stay', range: 'D+1 → D+n', from: 0.36, to: 0.66 },
  { id: 'departure', label: 'Departure', range: 'D+n', from: 0.66, to: 0.86 },
  { id: 'after', label: 'After the stay', range: 'D+1 → D+2', from: 0.86, to: 1.0 },
];

export const LANES_EN: Lane[] = [
  { id: 0, label: 'GUEST', sublabel: 'Guest', color: '#06b6d4' },
  { id: 1, label: 'SOJORI', sublabel: 'Orchestrator', color: '#e6b022' },
  { id: 2, label: 'STAFF', sublabel: 'Field team', color: '#8b5cf6' },
  { id: 3, label: 'ADMIN', sublabel: 'Supervisor', color: '#ef4444' },
];

export const EVENTS_EN: JourneyEvent[] = [
  {
    id: 'booking',
    t: 0.0,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🏠',
    title: 'Airbnb booking',
    sub: 'Sarah J. · 3 nights · €840',
    status: 'completed',
    anim: 'confetti',
    tag: 'D-14',
    transitions: [{ at: 0.02, status: 'completed', sub: 'Auto sync → calendar · payment confirmed', tag: 'Synced' }],
  },
  {
    id: 'staff-prep',
    t: 0.03,
    lane: 2,
    phase: 'before',
    type: 'staff',
    icon: '👨‍🔧',
    title: 'Property prep',
    sub: 'Lucas · quality check',
    status: 'active',
    anim: 'slide-right',
    tag: 'D-1',
    avatar: 'L',
    transitions: [{ at: 0.06, status: 'completed', sub: 'Quality ✓ · stock ✓ · keys ✓', tag: 'Ready' }],
  },
  {
    id: 'welcome',
    t: 0.05,
    lane: 0,
    phase: 'before',
    type: 'message',
    icon: '📨',
    title: 'Welcome message',
    sub: '« Welcome to Paris! Your stay starts soon »',
    status: 'completed',
    anim: 'fade',
    tag: 'D-7',
  },
  {
    id: 'register',
    t: 0.08,
    lane: 1,
    phase: 'before',
    type: 'declaration',
    icon: '🔐',
    title: 'Registration',
    sub: 'KYC in progress…',
    status: 'pending',
    anim: 'pop',
    tag: 'In progress',
    transitions: [{ at: 0.14, status: 'completed', sub: 'Identity verified in 30 seconds', tag: 'Verified' }],
  },
  {
    id: 'arrival-slot',
    t: 0.12,
    lane: 0,
    phase: 'before',
    type: 'timeslot',
    icon: '🎫',
    title: 'Arrival window',
    sub: '4:00 PM — 5:00 PM',
    status: 'info',
    anim: 'pop',
    tag: 'Timeslot',
    transitions: [{ at: 0.2, status: 'completed', tag: 'Confirmed' }],
  },
  {
    id: 'kids-club',
    t: 0.16,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '👶',
    title: 'Kids club requested',
    sub: 'Childcare service',
    status: 'pending',
    anim: 'pop',
    tag: 'Optional',
    transitions: [{ at: 0.21, status: 'completed', sub: 'Kids club booked · 2 children', tag: 'Confirmed' }],
  },
  {
    id: 'airport-shuttle',
    t: 0.18,
    lane: 0,
    phase: 'before',
    type: 'request',
    icon: '✈️',
    title: 'Airport shuttle',
    sub: 'Arrival transfer request',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Transport',
    transitions: [{ at: 0.22, status: 'completed', sub: 'Driver confirmed · flight AA123', tag: 'Scheduled' }],
  },
  {
    id: 'arrived',
    t: 0.24,
    lane: 0,
    phase: 'arrival',
    type: 'declaration',
    icon: '🏨',
    title: 'Guest arrived',
    sub: 'GPS + QR · self-declared',
    status: 'completed',
    anim: 'pop',
    tag: 'Check-in day',
  },
  {
    id: 'admin-conflict',
    t: 0.27,
    lane: 3,
    phase: 'arrival',
    type: 'admin',
    icon: '⚠️',
    title: 'Schedule conflict',
    sub: 'Previous guest did not declare departure',
    status: 'late',
    anim: 'shake',
    tag: 'Blocked',
    transitions: [
      { at: 0.29, status: 'active', sub: 'Admin contacting departing guest · departure time?', tag: 'In progress', icon: '📞' },
      { at: 0.32, status: 'completed', sub: '2:00 PM checkout · 4:00 PM arrival OK', tag: 'Resolved', icon: '✓' },
    ],
  },
  {
    id: 'feedback',
    t: 0.38,
    lane: 0,
    phase: 'stay',
    type: 'message',
    icon: '💬',
    title: 'Feedback message',
    sub: '« How is your stay going? »',
    status: 'info',
    anim: 'bubble',
    tag: 'D+1',
  },
  {
    id: 'clean-mid',
    t: 0.42,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧹',
    title: 'Included clean — day 3',
    sub: 'Scheduled · reminder D-2',
    status: 'soon',
    anim: 'cascade',
    tag: 'Scheduled',
    transitions: [
      { at: 0.46, status: 'pending', sub: 'Soon · staff notified', tag: 'Soon' },
      { at: 0.5, status: 'active', sub: 'Sophie on the way', tag: 'Assigned', avatar: 'S' },
      { at: 0.55, status: 'completed', sub: 'Cleaning done · spotless', tag: 'OK', icon: '✅' },
    ],
  },
  {
    id: 'transport',
    t: 0.46,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🚗',
    title: 'Airport ride',
    sub: 'Guest request',
    status: 'pending',
    anim: 'slide-right',
    tag: 'Optional',
    transitions: [{ at: 0.52, status: 'completed', sub: 'Driver assigned · ETA 4:23 PM', tag: 'Confirmed' }],
  },
  {
    id: 'groceries',
    t: 0.5,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '🛍️',
    title: 'Groceries',
    sub: 'Guest request',
    status: 'pending',
    anim: 'pop',
    tag: 'Optional',
    transitions: [{ at: 0.56, status: 'completed', sub: 'Fridge stocked before arrival', tag: 'Delivered' }],
  },
  {
    id: 'wifi-issue',
    t: 0.52,
    lane: 0,
    phase: 'stay',
    type: 'request',
    icon: '📶',
    title: 'Wi-Fi support ticket',
    sub: 'Connection issue reported',
    status: 'late',
    anim: 'shake',
    tag: 'Urgent',
    transitions: [
      { at: 0.52, status: 'active', sub: 'Staff assigned immediately · Marc on the way', tag: 'Assigned', avatar: 'M' },
      { at: 0.54, status: 'active', sub: 'Technician on site · diagnosing', tag: 'In progress' },
      { at: 0.56, status: 'completed', sub: 'Wi-Fi restored · speed test OK', tag: 'Resolved' },
    ],
  },
  {
    id: 'support',
    t: 0.54,
    lane: 1,
    phase: 'stay',
    type: 'request',
    icon: '✨',
    title: 'Dedicated support',
    sub: 'Private concierge',
    status: 'active',
    anim: 'pop',
    tag: 'Premium',
  },
  {
    id: 'extra-clean',
    t: 0.58,
    lane: 2,
    phase: 'stay',
    type: 'cleaning',
    icon: '🧼',
    title: 'Extra cleaning',
    sub: 'On-demand service',
    status: 'pending',
    anim: 'cascade',
    tag: 'EXTRA · €25',
    transitions: [{ at: 0.63, status: 'completed', sub: 'Cleaning done · 28 min', tag: 'Done' }],
  },
  {
    id: 'depart-instr',
    t: 0.68,
    lane: 0,
    phase: 'departure',
    type: 'message',
    icon: '📋',
    title: 'Checkout instructions',
    sub: '« Everything you need to know »',
    status: 'info',
    anim: 'fade',
    tag: 'D-1',
  },
  {
    id: 'depart-slot',
    t: 0.71,
    lane: 0,
    phase: 'departure',
    type: 'timeslot',
    icon: '🎫',
    title: 'Departure window',
    sub: '11:00 AM',
    status: 'info',
    anim: 'pop',
    tag: 'Timeslot',
    transitions: [{ at: 0.76, status: 'completed', tag: 'Confirmed' }],
  },
  {
    id: 'staff-late',
    t: 0.73,
    lane: 3,
    phase: 'departure',
    type: 'admin',
    icon: '🚨',
    title: 'Staff no-show',
    sub: 'Reassignment needed',
    status: 'late',
    anim: 'shake',
    tag: 'Urgent',
    transitions: [{ at: 0.78, status: 'completed', sub: 'Reassigned to Marc · 2 min', tag: 'Resolved', icon: '👨‍💼' }],
  },
  {
    id: 'departed',
    t: 0.79,
    lane: 0,
    phase: 'departure',
    type: 'declaration',
    icon: '✅',
    title: 'Guest departed',
    sub: 'Checkout declared',
    status: 'completed',
    anim: 'confetti',
    tag: 'Done',
  },
  {
    id: 'final-clean',
    t: 0.81,
    lane: 2,
    phase: 'departure',
    type: 'cleaning',
    icon: '🧹',
    title: 'Final Sojori clean',
    sub: '2h left before next booking',
    status: 'late',
    anim: 'priority',
    tag: 'PRIORITY',
    priority: true,
    transitions: [
      { at: 0.84, status: 'pending', sub: '1h30 · Marc on site', tag: 'In progress', avatar: 'M' },
      {
        at: 0.86,
        status: 'completed',
        sub: 'Ready for next reservation · property set',
        tag: '✓ Ready',
        icon: '✅',
        priority: false,
      },
    ],
  },
  {
    id: 'thanks',
    t: 0.88,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '🙏',
    title: 'Thank-you message',
    sub: '« See you soon with Sojori »',
    status: 'info',
    anim: 'fade',
    tag: 'D+1',
  },
  {
    id: 'review',
    t: 0.93,
    lane: 0,
    phase: 'after',
    type: 'message',
    icon: '⭐',
    title: 'Review request',
    sub: '5-star review received',
    status: 'completed',
    anim: 'stars',
    tag: 'D+2',
  },
];
